openapi: 3.0.0
info:
  description: User API example
  version: 1.0.0
  title: User API example
paths:

  /users:
    get:
      security: 
      - bearerAuth: []
      tags: 
        - user
      summary: List users
      description: This endpoint list the system users
      parameters: 
        - $ref: '#/components/parameters/limitParam'
        - name: name 
          in: query
          description: 'Filter for search by user name'
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    post:
      security: 
      - bearerAuth: []
      tags:
        - user
      summary: Create a user
      description: This endpoint creates a user
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'




components:

  parameters:
        
    limitParam:
      name: limit
      in: query
      description: "Number of records to retrieve"
      example: 50
      schema:
        type: integer    


  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      
  schemas:    
 
    User:
      type: object
      required: 
        - email
        - password
        - country
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        username:
          type: string
        password:
          type: string
          format: password
        email:
          type: string
          format: email
        country:
          type: string
            
            
    Error:
      type: object
      properties:
        code:
          description: Error code
          type: string
        status:
          description: httpstatus
          type: integer
          format: int32
        type:
          type: string
          description: Error type
        message:
          type: string
          description: Error message